- name: Install Network Manager
  become: true
  pacman:
    name: networkmanager
    state: present

- name: Start Network Manager service and enable it
  become: true
  systemd:
    name: NetworkManager
    state: started
    enabled: true

- name: Install curl and wget
  become: true
  pacman:
    name:
      - curl
      - wget
    state: present

- name: Install DNS utils
  become: true
  pacman:
    name: dnsutils
    state: present

- name: Install UFW
  pacman:
    name: ufw
    state: present
  become: true
- name: Deny everything and enable UFW
  ufw:
    state: enabled
    policy: deny
  become: true

- name: Install ssh
  become: true
  pacman:
    name: openssh
    state: present