---
- set_fact:
    repo_directory: "{{ ansible_env.HOME }}/.dotfiles"

- name: Clone dotfiles repo
  git:
    repo: https://github.com/phillebaba/dotfiles.git
    dest: "{{ repo_directory }}"
    clone: true
    update: true

- set_fact:
    dotfiles_directory: "{{ repo_directory }}/files/"

- name: Recursively find all files
  find:
    paths: "{{ dotfiles_directory }}"
    recurse: true
  register: dotfiles

- name: Create directories if missing
  file:
    path: "{{ ansible_env.HOME }}/{{ item.path | replace(dotfiles_directory, '') | dirname }}"
    state: directory
  with_items: "{{ dotfiles.files }}"

- name: Symlink dotfiles
  file:
    src: "{{ item.path }}"
    dest: "{{ ansible_env.HOME }}/{{ item.path | replace(dotfiles_directory, '') }}"
    state: link
    force: true
  with_items: "{{ dotfiles.files }}"
