- name: Install stow
  become: true
  pacman:
    name: stow
    state: present

- name: Check if dotfiles has been cloned
  stat:
    path: "{{ dotfiles_directory }}"
  register: dotfiles

- block:
    - name: Clone dotfiles repo
      git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ dotfiles_directory }}"
        clone: true
  when: dotfiles.stat.exists == false

- name: Get directories in dotfiles
  find:
    paths: "{{ dotfiles_directory }}"
    file_type: directory
    recurse: false
  register: directories

- debug:
    var: directories

- name: Stow all directories in dotfiles
  command: stow "{{ item.path | basename }}"
  args:
    chdir: "{{ dotfiles_directory }}"
  with_items: "{{ directories.files }}"
