# https://wiki.archlinux.org/index.php/bluetooth
# https://wiki.archlinux.org/index.php/Bluetooth_headset

- name: Install bluetooth dependencies
  become: true
  pacman:
    name:
      - bluez
      - bluez-utils
    state: present

- name: Install audio dependencies
  become: true
  pacman:
    name:
      - pulseaudio-alsa
      - pulseaudio-bluetooth
    state: present

- name: Enable media controls
  block:
    - file:
        path: "{{ ansible_env.HOME}}/.config/systemd/user"
        state: directory

    - copy:
        dest: "{{ ansible_env.HOME}}/.config/systemd/user/mpris-proxy.service"
        content: |
          [Unit]
          Description=Forward bluetooth midi controls via mpris2 so they are picked up by supporting media players

          [Service]
          Type=simple
          ExecStart=/usr/bin/mpris-proxy

          [Install]
          WantedBy=default.target

    - systemd:
        name: mpris-proxy
        state: started
        enabled: true
        scope: user
