- name: Install kitty terminal
  become: true
  pacman:
    name:
      - kitty
    state: present

- name: Install Firefox
  become: true
  pacman:
    name: firefox
    state: present

- name: Install Arandr
  become: true
  pacman:
    name: arandr
    state: present

- name: Install Zathura (PDF Viewer)
  become: true
  pacman:
    name: zathura
    state: present

- name: Install Slack
  command: yay --noconfirm -S aur/slack-desktop
