- name: Install Nerd Font
  shell: yay --needed --noconfirm -S nerd-fonts-inconsolata

- name: Install xorg dependencies
  become: true
  pacman:
    name:
      - xorg
      - xorg-xinit
      - xcompmgr
    state: present

- name: Install slock
  become: true
  pacman:
    name: slock
    state: present

- name: Install Dunst (Notification Daemon)
  become: true
  pacman:
    name: dunst
    state: present

- name: Install pywal
  pip:
    name: pywal
    extra_args: --user

- name: Install Feh
  become: true
  pacman:
    name: feh
    state: present

- name: DWM Setup
  block:
    - name: Clone DWM repo
      git:
        repo: "https://github.com/phillebaba/dwm.git"
        dest: "{{ ansible_env.HOME }}/dev/dwm"
        refspec: "patches"
    - name: Install DWM
      command: make clean install
      args:
        chdir: "{{ ansible_env.HOME }}/dev/dwm"
      become: true
