- name: Install Nerd Font
  shell: yay --needed --noconfirm -S aur/nerd-fonts-complete
  args:
    creates: /usr/share/fonts/nerd-fonts-complete

- name: Install xorg dependencies
  become: true
  pacman:
    name: ["xorg", "xorg-xinit"]
    state: present

- name: Install i3WM and addons
  become: true
  pacman:
    name: ["i3-gaps", "rofi"]
    state: present

- name: Install polybar
  shell: yay --noconfirm -S aur/polybar

- name: Install Dunst (Notification Daemon)
  become: true
  pacman:
    name: dunst
    state: present

- name: Install pywal
  pip:
    name: pywal
    extra_args: --user

- name: Install Feh
  become: true
  pacman:
    name: feh
    state: present

- name: Install Compton
  become: true
  pacman:
    name: compton
    state: present

- name: Install betterlockscreen
  shell: yay --needed --noconfirm -S aur/betterlockscreen

- name: Enable betterlockscreen auto lock service
  become: true
  service:
    name: "betterlockscreen@{{ ansible_user }}"
    state: started
    enabled: true
