- name: Install Nerd Font
  shell: yay --needed --noconfirm -S nerd-fonts-inconsolata
  args:
    creates: /usr/share/fonts/nerd-fonts-complete

- name: Install xorg dependencies
  become: true
  pacman:
    name:
      - xorg
      - xorg-xinit
      - xcompmgr
    state: present

- name: Install slock
  become: true
  pacman:
    name: slock
    state: present

- name: Install Dunst (Notification Daemon)
  become: true
  pacman:
    name: dunst
    state: present

- name: Install pywal
  pip:
    name: pywal
    extra_args: --user

- name: Install Feh
  become: true
  pacman:
    name: feh
    state: present
