- name: Set as default locale
  become: true
  command: localectl set-locale LANG=en_US.UTF-8

- name: Disable root login
  shell: passwd -l root
  become: true

- name: Blacklist pcspkr from being loaded by kernel (beep)
  become: true
  copy:
    content: blacklist pcspkr
    dest: /etc/modprobe.d/nobeep.conf

- name: Configure mirror updating
  block:
    - name: Install reflector
      become: true
      pacman:
        name: reflector
        state: present
    - name: Create service configuration
      copy:
        dest: "/etc/systemd/system/reflector.service"
        content: |
          [Unit]
          Description=Pacman mirrorlist update
          Wants=network-online.target
          After=network-online.target

          [Service]
          Type=oneshot
          ExecStart=/usr/bin/reflector --protocol https --latest 30 --number 20 --sort rate --save /etc/pacman.d/mirrorlist

          [Install]
          RequiredBy=multi-user.target
      become: true
    - name: Start and enable relector service
      service:
        name: reflector
        enabled: true
      become: true

- name: Install yay
  block:
    - tempfile:
        state: directory
      register: temp
    - shell: |
        git clone https://aur.archlinux.org/yay.git
        cd yay
        makepkg -si --noconfirm
      args:
        chdir: "{{ temp.path }}"
        creates: /usr/bin/yay

- name: Login Manager
  block:
    - name: Install ly
      shell: yay --needed --noconfirm -S ly
      args:
        creates: /sbin/ly
    - name: Enable ly service
      become: true
      service:
        name: ly
        enabled: true

- name: Audio
  block:
    - name: Install pipewire
      become: true
      pacman:
        name:
          - wireplumber
          - pipewire
          - pipewire-alsa
          - pipewire-pulse
          - pipewire-jack
          - helvum
          - pavucontrol
          - bluez
          - bluez-utils
          - mpd
        state: present
    - name: Start and enable mpd service
      become: true
      service:
        name: mpd
        enabled: true
    - name: Start and enable bluetooth service
      become: true
      service:
        name: bluetooth
        enabled: true
