- name: Install NetworkManager
  become: true
  pacman:
    name: networkmanager
    state: present

- name: Start networkmanager service and enable it
  become: true
  systemd:
    name: NetworkManager
    state: started
    enabled: true

- name: Install curl and wget
  become: true
  pacman:
    name:
      - curl
      - wget
    state: present

- name: Install DNS utils
  become: true
  pacman:
    name: dnsutils
    state: present
