window:
  padding:
    x: 5
    y: 5

scrolling:
  history: 10000

font:
  size: 11.0
  normal:
    family: FiraCode Nerd Font
  bold:
    family: FiraCode Nerd Font
  italic:
    family: FiraCode Nerd Font
