- name: Install Firefox
  become: true
  pacman:
    name: firefox
    state: present

- name: Install Zathura (PDF Viewer)
  become: true
  pacman:
    name: zathura
    state: present

- name: Install Slack
  command: yay --noconfirm -S aur/slack-desktop
  args:
    creates: /sbin/slack

- name: Install Spotify
  command: yay --noconfirm -S spotify
  args:
    creates: /sbin/spotify