- name: Install terraform
  shell: yay --needed --noconfirm -S tfenv
  #args:
  #  creates: /usr/bin/river

- name: Install AWS CLI
  shell: yay --needed --noconfirm -S aws-cli-v2-bin
  args:
    creates: /sbin/aws
