- name: Install aws cli
  pip:
    name: awscli
    state: present
    extra_args: --user

- name: Install Azure CLI
  shell: yay --noconfirm -S azure-cli

- name: Install terraform
  become: true
  pacman:
    name: terraform
    state: present
