- name: Install tfenv
  shell: yay --needed --noconfirm -S tfenv
  args:
    creates: /sbin/tfenv

- name: Install AWS CLI
  shell: yay --needed --noconfirm -S aws-cli-v2-bin
  args:
    creates: /sbin/aws

- name: Install Azure CLI
  shell: yay --needed --noconfirm -S azure-cli
  args:
    creates: /sbin/az
