- name: Install kubectl
  become: true
  pacman:
    name: kubectl
    state: present

- name: Install kubectx
  become: true
  pacman:
    name: kubectx
    state: present

- name: Install kustomize
  shell: yay --noconfirm -S kustomize-bin

- name: Install eksctl
  shell: yay --noconfirm -S eksctl

- name: Install kind
  shell: yay --noconfirm -S kind
