- name: Install zsh shell
  become: true
  pacman:
    name: zsh
    state: present

- name: Set zsh as default shell
  block:
    - command: whoami
      register: current_user
    - user:
        name: "{{ current_user.stdout }}"
        shell: /usr/bin/zsh
      become: true

- name: Install-oh my-zsh
  shell: yay --noconfirm -S oh-my-zsh-git

- name: Install zsh-autosuggestions
  become: true
  pacman:
    name: zsh-autosuggestions
    state: present
