- name: Install base-devel
  become: true
  pacman:
    name: base-devel
    state: present

- name: Install git
  become: true
  pacman:
    name: git
    state: present

- name: Install yay
  block:
    - tempfile:
        state: directory
      register: temp
    - shell: |
        git clone https://aur.archlinux.org/yay.git
        cd yay
        makepkg -si --noconfirm
      args:
        chdir: "{{ temp.path }}"
        creates: /usr/bin/yay
