- name: Create user directories
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - downloads
    - code
    - documents
    - pictures

- name: Install stow
  become: true
  pacman:
    name: stow
    state: present

- name: Check if dotfiles has been cloned
  stat:
    path: "{{ dotfiles_directory }}"
  register: dotfiles

- name: Clone dotfiles repo
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_directory }}"
    clone: true
  when: dotfiles.stat.exists == false

- name: Stow all directories in dotfiles
  command: "stow --target={{ ansible_env.HOME }} --dir={{ dotfiles_directory }} ."
  args:
    chdir: "{{ ansible_env.HOME }}"
