- name: Assert that mandatory variables are defined
  assert:
    that:
      - timezone is defined # Timezone in the format of Zone/SubZone
      - locales is defined # One or more locales in /etc/locale.conf
      - keyboard_layout is defined
      - hostname is defined

- name: Set timezone
  become: true
  file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    state: link

- name: Set the Hardware Clock from the System Clock
  become: true
  command: hwclock --systohc

- name: Set and generate locales
  become: true
  locale_gen:
    name: "{{ locales }}"
    state: present

- name: Set keyboard layout
  become: true
  command: "localectl set-keymap --no-convert {{ keyboard_layout }}"

- name: Set computer hostname
  become: true
  copy:
    content: "{{ hostname }}"
    dest: "/etc/hostname"

- name: Create user directories
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - downloads
    - code
    - documents
    - pictures
