- name: Assert that mandatory variables are defined
  assert:
    that:
      - timezone is defined # Timezone in the format of Zone/SubZone
      - locales is defined # One or more locales in /etc/locale.conf
      - keyboard_layout is defined
      - hostname is defined

- import_tasks: system.yaml
- import_tasks: security.yaml
- import_tasks: dotfiles.yaml
