---
- name: Install git
  become: true
  pacman:
    name: git
    state: present

- name: Install base font
  become: true
  pacman:
    name: ttf-dejavu
    state: present

- name: Install yay
  become: true
  shell: |
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -si
    cd ..
    rm -rf yay
