---
- name: Install zsh shell
  become: true
  pacman:
    name: zsh
    state: present

- name: Set zsh as default shell
  become: true
  shell: chsh -s /usr/bin/zsh

- name: Install Oh My Zsh
  become: true
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"

- name: Install zsh-autosuggestions
  become: true
  pacman:
    name: zsh-autosuggestions
    state: present
